// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6gHOHrMhkfBIPqsBAwa8keScjuMJR1Q',
    appId: '1:599799297587:web:a6fbccdc585bf25c529546',
    messagingSenderId: '599799297587',
    projectId: 'quiz-95636',
    authDomain: 'quiz-95636.firebaseapp.com',
    storageBucket: 'quiz-95636.appspot.com',
    measurementId: 'G-M5ECC3FDMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFUH4VcMKl3qIeK2Of5fz9yJb-jcr-IX8',
    appId: '1:599799297587:android:d1713112d26835e5529546',
    messagingSenderId: '599799297587',
    projectId: 'quiz-95636',
    storageBucket: 'quiz-95636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp1jyB79V_MZZm43utyRIkdILo13YzG44',
    appId: '1:599799297587:ios:b243630bb5d76edc529546',
    messagingSenderId: '599799297587',
    projectId: 'quiz-95636',
    storageBucket: 'quiz-95636.appspot.com',
    iosBundleId: 'com.hariapp.untitled10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp1jyB79V_MZZm43utyRIkdILo13YzG44',
    appId: '1:599799297587:ios:e70a2fc25deed083529546',
    messagingSenderId: '599799297587',
    projectId: 'quiz-95636',
    storageBucket: 'quiz-95636.appspot.com',
    iosBundleId: 'com.hariapp.untitled10.RunnerTests',
  );
}
